[heltec_v4_base] 
extends = esp32s3_base
board = heltec_v4
board_build.partitions = default_16MB.csv
build_flags = 
  ${esp32s3_base.build_flags}
  -D HELTEC_V4
  -D HAS_LORA_FEM=1
  -I variants/esp32s3/heltec_v4


[env:heltec-v4]
custom_meshtastic_hw_model = 110
custom_meshtastic_hw_model_slug = HELTEC_V4
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Heltec V4
custom_meshtastic_images = heltec_v4.svg
custom_meshtastic_tags = Heltec
custom_meshtastic_requires_dfu = true
custom_meshtastic_partition_scheme = 16MB
custom_meshtastic_has_mui = true

extends = heltec_v4_base
board_level = release
custom_sdkconfig =
  ${esp32s3_base.custom_sdkconfig}
  CONFIG_PM_ENABLE=y
build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/heltec_v4>
build_flags =
  ${heltec_v4_base.build_flags}
  -D HELTEC_V4_OLED
  -D GPS_DEFAULT_DISABLED
  -D USE_SSD1306 ; Heltec_v4 has an SSD1315 display (compatible with SSD1306 driver)
  -D LED_POWER=35
  -D RESET_OLED=21
  -D I2C_SDA=17
  -D I2C_SCL=18
  -D I2C_SDA1=4
  -D I2C_SCL1=3
